// Code generated by tools/ts_ast_codegen. DO NOT EDIT.

/// Lexical token and AST node kinds.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u16)]
pub enum SyntaxKind {
    Unknown = 0,
    EndOfFile = 1,
    SingleLineCommentTrivia = 2,
    MultiLineCommentTrivia = 3,
    NewLineTrivia = 4,
    WhitespaceTrivia = 5,
    ConflictMarkerTrivia = 6,
    NonTextFileMarkerTrivia = 7,
    NumericLiteral = 8,
    BigIntLiteral = 9,
    StringLiteral = 10,
    JsxText = 11,
    JsxTextAllWhiteSpaces = 12,
    RegularExpressionLiteral = 13,
    NoSubstitutionTemplateLiteral = 14,
    // Pseudo-literals
    TemplateHead = 15,
    TemplateMiddle = 16,
    TemplateTail = 17,
    // Punctuation
    OpenBraceToken = 18,
    CloseBraceToken = 19,
    OpenParenToken = 20,
    CloseParenToken = 21,
    OpenBracketToken = 22,
    CloseBracketToken = 23,
    DotToken = 24,
    DotDotDotToken = 25,
    SemicolonToken = 26,
    CommaToken = 27,
    QuestionDotToken = 28,
    LessThanToken = 29,
    LessThanSlashToken = 30,
    GreaterThanToken = 31,
    LessThanEqualsToken = 32,
    GreaterThanEqualsToken = 33,
    EqualsEqualsToken = 34,
    ExclamationEqualsToken = 35,
    EqualsEqualsEqualsToken = 36,
    ExclamationEqualsEqualsToken = 37,
    EqualsGreaterThanToken = 38,
    PlusToken = 39,
    MinusToken = 40,
    AsteriskToken = 41,
    AsteriskAsteriskToken = 42,
    SlashToken = 43,
    PercentToken = 44,
    PlusPlusToken = 45,
    MinusMinusToken = 46,
    LessThanLessThanToken = 47,
    GreaterThanGreaterThanToken = 48,
    GreaterThanGreaterThanGreaterThanToken = 49,
    AmpersandToken = 50,
    BarToken = 51,
    CaretToken = 52,
    ExclamationToken = 53,
    TildeToken = 54,
    AmpersandAmpersandToken = 55,
    BarBarToken = 56,
    QuestionToken = 57,
    ColonToken = 58,
    AtToken = 59,
    QuestionQuestionToken = 60,
    // Only the JSDoc scanner produces BacktickToken. The normal scanner produces NoSubstitutionTemplateLiteral and related kinds.
    BacktickToken = 61,
    // Only the JSDoc scanner produces HashToken. The normal scanner produces PrivateIdentifier.
    HashToken = 62,
    // Assignments
    EqualsToken = 63,
    PlusEqualsToken = 64,
    MinusEqualsToken = 65,
    AsteriskEqualsToken = 66,
    AsteriskAsteriskEqualsToken = 67,
    SlashEqualsToken = 68,
    PercentEqualsToken = 69,
    LessThanLessThanEqualsToken = 70,
    GreaterThanGreaterThanEqualsToken = 71,
    GreaterThanGreaterThanGreaterThanEqualsToken = 72,
    AmpersandEqualsToken = 73,
    BarEqualsToken = 74,
    BarBarEqualsToken = 75,
    AmpersandAmpersandEqualsToken = 76,
    QuestionQuestionEqualsToken = 77,
    CaretEqualsToken = 78,
    // Identifiers and PrivateIdentifier
    Identifier = 79,
    PrivateIdentifier = 80,
    JsDocCommentTextToken = 81,
    // Reserved words
    BreakKeyword = 82,
    CaseKeyword = 83,
    CatchKeyword = 84,
    ClassKeyword = 85,
    ConstKeyword = 86,
    ContinueKeyword = 87,
    DebuggerKeyword = 88,
    DefaultKeyword = 89,
    DeleteKeyword = 90,
    DoKeyword = 91,
    ElseKeyword = 92,
    EnumKeyword = 93,
    ExportKeyword = 94,
    ExtendsKeyword = 95,
    FalseKeyword = 96,
    FinallyKeyword = 97,
    ForKeyword = 98,
    FunctionKeyword = 99,
    IfKeyword = 100,
    ImportKeyword = 101,
    InKeyword = 102,
    InstanceOfKeyword = 103,
    NewKeyword = 104,
    NullKeyword = 105,
    ReturnKeyword = 106,
    SuperKeyword = 107,
    SwitchKeyword = 108,
    ThisKeyword = 109,
    ThrowKeyword = 110,
    TrueKeyword = 111,
    TryKeyword = 112,
    TypeOfKeyword = 113,
    VarKeyword = 114,
    VoidKeyword = 115,
    WhileKeyword = 116,
    WithKeyword = 117,
    // Strict mode reserved words
    ImplementsKeyword = 118,
    InterfaceKeyword = 119,
    LetKeyword = 120,
    PackageKeyword = 121,
    PrivateKeyword = 122,
    ProtectedKeyword = 123,
    PublicKeyword = 124,
    StaticKeyword = 125,
    YieldKeyword = 126,
    // Contextual keywords
    AbstractKeyword = 127,
    AccessorKeyword = 128,
    AsKeyword = 129,
    AssertsKeyword = 130,
    AssertKeyword = 131,
    AnyKeyword = 132,
    AsyncKeyword = 133,
    AwaitKeyword = 134,
    BooleanKeyword = 135,
    ConstructorKeyword = 136,
    DeclareKeyword = 137,
    GetKeyword = 138,
    ImmediateKeyword = 139,
    InferKeyword = 140,
    IntrinsicKeyword = 141,
    IsKeyword = 142,
    KeyOfKeyword = 143,
    ModuleKeyword = 144,
    NamespaceKeyword = 145,
    NeverKeyword = 146,
    OutKeyword = 147,
    ReadonlyKeyword = 148,
    RequireKeyword = 149,
    NumberKeyword = 150,
    ObjectKeyword = 151,
    SatisfiesKeyword = 152,
    SetKeyword = 153,
    StringKeyword = 154,
    SymbolKeyword = 155,
    TypeKeyword = 156,
    UndefinedKeyword = 157,
    UniqueKeyword = 158,
    UnknownKeyword = 159,
    UsingKeyword = 160,
    FromKeyword = 161,
    GlobalKeyword = 162,
    BigIntKeyword = 163,
    OverrideKeyword = 164,
    OfKeyword = 165,
    DeferKeyword = 166, // LastKeyword and LastToken and LastContextualKeyword
    // Parse tree nodes
    // Names
    QualifiedName = 167,
    ComputedPropertyName = 168,
    // Signature elements
    TypeParameter = 169,
    Parameter = 170,
    Decorator = 171,
    // TypeMember
    PropertySignature = 172,
    PropertyDeclaration = 173,
    MethodSignature = 174,
    MethodDeclaration = 175,
    ClassStaticBlockDeclaration = 176,
    Constructor = 177,
    GetAccessor = 178,
    SetAccessor = 179,
    CallSignature = 180,
    ConstructSignature = 181,
    IndexSignature = 182,
    // Type
    TypePredicate = 183,
    TypeReference = 184,
    FunctionType = 185,
    ConstructorType = 186,
    TypeQuery = 187,
    TypeLiteral = 188,
    ArrayType = 189,
    TupleType = 190,
    OptionalType = 191,
    RestType = 192,
    UnionType = 193,
    IntersectionType = 194,
    ConditionalType = 195,
    InferType = 196,
    ParenthesizedType = 197,
    ThisType = 198,
    TypeOperator = 199,
    IndexedAccessType = 200,
    MappedType = 201,
    LiteralType = 202,
    NamedTupleMember = 203,
    TemplateLiteralType = 204,
    TemplateLiteralTypeSpan = 205,
    ImportType = 206,
    // Binding patterns
    ObjectBindingPattern = 207,
    ArrayBindingPattern = 208,
    BindingElement = 209,
    // Expression
    ArrayLiteralExpression = 210,
    ObjectLiteralExpression = 211,
    PropertyAccessExpression = 212,
    ElementAccessExpression = 213,
    CallExpression = 214,
    NewExpression = 215,
    TaggedTemplateExpression = 216,
    TypeAssertionExpression = 217,
    ParenthesizedExpression = 218,
    FunctionExpression = 219,
    ArrowFunction = 220,
    DeleteExpression = 221,
    TypeOfExpression = 222,
    VoidExpression = 223,
    AwaitExpression = 224,
    PrefixUnaryExpression = 225,
    PostfixUnaryExpression = 226,
    BinaryExpression = 227,
    ConditionalExpression = 228,
    TemplateExpression = 229,
    YieldExpression = 230,
    SpreadElement = 231,
    ClassExpression = 232,
    OmittedExpression = 233,
    ExpressionWithTypeArguments = 234,
    AsExpression = 235,
    NonNullExpression = 236,
    MetaProperty = 237,
    SyntheticExpression = 238,
    SatisfiesExpression = 239,
    // Misc
    TemplateSpan = 240,
    SemicolonClassElement = 241,
    // Element
    Block = 242,
    EmptyStatement = 243,
    VariableStatement = 244,
    ExpressionStatement = 245,
    IfStatement = 246,
    DoStatement = 247,
    WhileStatement = 248,
    ForStatement = 249,
    ForInStatement = 250,
    ForOfStatement = 251,
    ContinueStatement = 252,
    BreakStatement = 253,
    ReturnStatement = 254,
    WithStatement = 255,
    SwitchStatement = 256,
    LabeledStatement = 257,
    ThrowStatement = 258,
    TryStatement = 259,
    DebuggerStatement = 260,
    VariableDeclaration = 261,
    VariableDeclarationList = 262,
    FunctionDeclaration = 263,
    ClassDeclaration = 264,
    InterfaceDeclaration = 265,
    TypeAliasDeclaration = 266,
    EnumDeclaration = 267,
    ModuleDeclaration = 268,
    ModuleBlock = 269,
    CaseBlock = 270,
    NamespaceExportDeclaration = 271,
    ImportEqualsDeclaration = 272,
    ImportDeclaration = 273,
    ImportClause = 274,
    NamespaceImport = 275,
    NamedImports = 276,
    ImportSpecifier = 277,
    ExportAssignment = 278,
    ExportDeclaration = 279,
    NamedExports = 280,
    NamespaceExport = 281,
    ExportSpecifier = 282,
    MissingDeclaration = 283,
    // Module references
    ExternalModuleReference = 284,
    // JSX
    JsxElement = 285,
    JsxSelfClosingElement = 286,
    JsxOpeningElement = 287,
    JsxClosingElement = 288,
    JsxFragment = 289,
    JsxOpeningFragment = 290,
    JsxClosingFragment = 291,
    JsxAttribute = 292,
    JsxAttributes = 293,
    JsxSpreadAttribute = 294,
    JsxExpression = 295,
    JsxNamespacedName = 296,
    // Clauses
    CaseClause = 297,
    DefaultClause = 298,
    HeritageClause = 299,
    CatchClause = 300,
    // Import attributes
    ImportAttributes = 301,
    ImportAttribute = 302,
    // Property assignments
    PropertyAssignment = 303,
    ShorthandPropertyAssignment = 304,
    SpreadAssignment = 305,
    // Enum
    EnumMember = 306,
    // Top-level nodes
    SourceFile = 307,
    // JSDoc nodes
    JsDocTypeExpression = 308,
    JsDocNameReference = 309,
    JsDocAllType = 310, // The * type
    JsDocNullableType = 311,
    JsDocNonNullableType = 312,
    JsDocOptionalType = 313,
    JsDocVariadicType = 314,
    JsDoc = 315,
    JsDocText = 316,
    JsDocTypeLiteral = 317,
    JsDocSignature = 318,
    JsDocLink = 319,
    JsDocLinkCode = 320,
    JsDocLinkPlain = 321,
    JsDocUnknownTag = 322,
    JsDocAugmentsTag = 323,
    JsDocImplementsTag = 324,
    JsDocDeprecatedTag = 325,
    JsDocPublicTag = 326,
    JsDocPrivateTag = 327,
    JsDocProtectedTag = 328,
    JsDocReadonlyTag = 329,
    JsDocOverrideTag = 330,
    JsDocCallbackTag = 331,
    JsDocOverloadTag = 332,
    JsDocParameterTag = 333,
    JsDocReturnTag = 334,
    JsDocThisTag = 335,
    JsDocTypeTag = 336,
    JsDocTemplateTag = 337,
    JsDocTypedefTag = 338,
    JsDocSeeTag = 339,
    JsDocPropertyTag = 340,
    JsDocThrowsTag = 341,
    JsDocSatisfiesTag = 342,
    JsDocImportTag = 343,
    // Synthesized list
    SyntaxList = 344,
    // Reparsed JS nodes
    JsTypeAliasDeclaration = 345,
    JsImportDeclaration = 346,
    // Transformation nodes
    NotEmittedStatement = 347,
    PartiallyEmittedExpression = 348,
    SyntheticReferenceExpression = 349,
    NotEmittedTypeElement = 350,
}

impl SyntaxKind {
    pub const COUNT: usize = 351;
    pub const FIRST_ASSIGNMENT: Self = Self::EqualsToken;
    pub const LAST_ASSIGNMENT: Self = Self::CaretEqualsToken;
    pub const FIRST_COMPOUND_ASSIGNMENT: Self = Self::PlusEqualsToken;
    pub const LAST_COMPOUND_ASSIGNMENT: Self = Self::CaretEqualsToken;
    pub const FIRST_RESERVED_WORD: Self = Self::BreakKeyword;
    pub const LAST_RESERVED_WORD: Self = Self::WithKeyword;
    pub const FIRST_KEYWORD: Self = Self::BreakKeyword;
    pub const LAST_KEYWORD: Self = Self::DeferKeyword;
    pub const FIRST_FUTURE_RESERVED_WORD: Self = Self::ImplementsKeyword;
    pub const LAST_FUTURE_RESERVED_WORD: Self = Self::YieldKeyword;
    pub const FIRST_TYPE_NODE: Self = Self::TypePredicate;
    pub const LAST_TYPE_NODE: Self = Self::ImportType;
    pub const FIRST_PUNCTUATION: Self = Self::OpenBraceToken;
    pub const LAST_PUNCTUATION: Self = Self::CaretEqualsToken;
    pub const FIRST_TOKEN: Self = Self::Unknown;
    pub const LAST_TOKEN: Self = Self::LAST_KEYWORD;
    pub const FIRST_LITERAL_TOKEN: Self = Self::NumericLiteral;
    pub const LAST_LITERAL_TOKEN: Self = Self::NoSubstitutionTemplateLiteral;
    pub const FIRST_TEMPLATE_TOKEN: Self = Self::NoSubstitutionTemplateLiteral;
    pub const LAST_TEMPLATE_TOKEN: Self = Self::TemplateTail;
    pub const FIRST_BINARY_OPERATOR: Self = Self::LessThanToken;
    pub const LAST_BINARY_OPERATOR: Self = Self::CaretEqualsToken;
    pub const FIRST_STATEMENT: Self = Self::VariableStatement;
    pub const LAST_STATEMENT: Self = Self::DebuggerStatement;
    pub const FIRST_NODE: Self = Self::QualifiedName;
    pub const FIRST_JS_DOC_NODE: Self = Self::JsDocTypeExpression;
    pub const LAST_JS_DOC_NODE: Self = Self::JsDocImportTag;
    pub const FIRST_JS_DOC_TAG_NODE: Self = Self::JsDocUnknownTag;
    pub const LAST_JS_DOC_TAG_NODE: Self = Self::JsDocImportTag;
    pub const FIRST_CONTEXTUAL_KEYWORD: Self = Self::AbstractKeyword;
    pub const LAST_CONTEXTUAL_KEYWORD: Self = Self::DeferKeyword;
    pub const LAST_UNARY_OPERATOR: Self = Self::TildeToken;
    pub const FIRST_TRIVIA_TOKEN: Self = Self::SingleLineCommentTrivia;
    pub const LAST_TRIVIA_TOKEN: Self = Self::ConflictMarkerTrivia;

    #[allow(clippy::too_many_lines)]
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::EndOfFile => "EndOfFile",
            Self::SingleLineCommentTrivia => "SingleLineCommentTrivia",
            Self::MultiLineCommentTrivia => "MultiLineCommentTrivia",
            Self::NewLineTrivia => "NewLineTrivia",
            Self::WhitespaceTrivia => "WhitespaceTrivia",
            Self::ConflictMarkerTrivia => "ConflictMarkerTrivia",
            Self::NonTextFileMarkerTrivia => "NonTextFileMarkerTrivia",
            Self::NumericLiteral => "NumericLiteral",
            Self::BigIntLiteral => "BigIntLiteral",
            Self::StringLiteral => "StringLiteral",
            Self::JsxText => "JsxText",
            Self::JsxTextAllWhiteSpaces => "JsxTextAllWhiteSpaces",
            Self::RegularExpressionLiteral => "RegularExpressionLiteral",
            Self::NoSubstitutionTemplateLiteral => "NoSubstitutionTemplateLiteral",
            Self::TemplateHead => "TemplateHead",
            Self::TemplateMiddle => "TemplateMiddle",
            Self::TemplateTail => "TemplateTail",
            Self::OpenBraceToken => "OpenBraceToken",
            Self::CloseBraceToken => "CloseBraceToken",
            Self::OpenParenToken => "OpenParenToken",
            Self::CloseParenToken => "CloseParenToken",
            Self::OpenBracketToken => "OpenBracketToken",
            Self::CloseBracketToken => "CloseBracketToken",
            Self::DotToken => "DotToken",
            Self::DotDotDotToken => "DotDotDotToken",
            Self::SemicolonToken => "SemicolonToken",
            Self::CommaToken => "CommaToken",
            Self::QuestionDotToken => "QuestionDotToken",
            Self::LessThanToken => "LessThanToken",
            Self::LessThanSlashToken => "LessThanSlashToken",
            Self::GreaterThanToken => "GreaterThanToken",
            Self::LessThanEqualsToken => "LessThanEqualsToken",
            Self::GreaterThanEqualsToken => "GreaterThanEqualsToken",
            Self::EqualsEqualsToken => "EqualsEqualsToken",
            Self::ExclamationEqualsToken => "ExclamationEqualsToken",
            Self::EqualsEqualsEqualsToken => "EqualsEqualsEqualsToken",
            Self::ExclamationEqualsEqualsToken => "ExclamationEqualsEqualsToken",
            Self::EqualsGreaterThanToken => "EqualsGreaterThanToken",
            Self::PlusToken => "PlusToken",
            Self::MinusToken => "MinusToken",
            Self::AsteriskToken => "AsteriskToken",
            Self::AsteriskAsteriskToken => "AsteriskAsteriskToken",
            Self::SlashToken => "SlashToken",
            Self::PercentToken => "PercentToken",
            Self::PlusPlusToken => "PlusPlusToken",
            Self::MinusMinusToken => "MinusMinusToken",
            Self::LessThanLessThanToken => "LessThanLessThanToken",
            Self::GreaterThanGreaterThanToken => "GreaterThanGreaterThanToken",
            Self::GreaterThanGreaterThanGreaterThanToken => {
                "GreaterThanGreaterThanGreaterThanToken"
            }
            Self::AmpersandToken => "AmpersandToken",
            Self::BarToken => "BarToken",
            Self::CaretToken => "CaretToken",
            Self::ExclamationToken => "ExclamationToken",
            Self::TildeToken => "TildeToken",
            Self::AmpersandAmpersandToken => "AmpersandAmpersandToken",
            Self::BarBarToken => "BarBarToken",
            Self::QuestionToken => "QuestionToken",
            Self::ColonToken => "ColonToken",
            Self::AtToken => "AtToken",
            Self::QuestionQuestionToken => "QuestionQuestionToken",
            Self::BacktickToken => "BacktickToken",
            Self::HashToken => "HashToken",
            Self::EqualsToken => "EqualsToken",
            Self::PlusEqualsToken => "PlusEqualsToken",
            Self::MinusEqualsToken => "MinusEqualsToken",
            Self::AsteriskEqualsToken => "AsteriskEqualsToken",
            Self::AsteriskAsteriskEqualsToken => "AsteriskAsteriskEqualsToken",
            Self::SlashEqualsToken => "SlashEqualsToken",
            Self::PercentEqualsToken => "PercentEqualsToken",
            Self::LessThanLessThanEqualsToken => "LessThanLessThanEqualsToken",
            Self::GreaterThanGreaterThanEqualsToken => "GreaterThanGreaterThanEqualsToken",
            Self::GreaterThanGreaterThanGreaterThanEqualsToken => {
                "GreaterThanGreaterThanGreaterThanEqualsToken"
            }
            Self::AmpersandEqualsToken => "AmpersandEqualsToken",
            Self::BarEqualsToken => "BarEqualsToken",
            Self::BarBarEqualsToken => "BarBarEqualsToken",
            Self::AmpersandAmpersandEqualsToken => "AmpersandAmpersandEqualsToken",
            Self::QuestionQuestionEqualsToken => "QuestionQuestionEqualsToken",
            Self::CaretEqualsToken => "CaretEqualsToken",
            Self::Identifier => "Identifier",
            Self::PrivateIdentifier => "PrivateIdentifier",
            Self::JsDocCommentTextToken => "JSDocCommentTextToken",
            Self::BreakKeyword => "BreakKeyword",
            Self::CaseKeyword => "CaseKeyword",
            Self::CatchKeyword => "CatchKeyword",
            Self::ClassKeyword => "ClassKeyword",
            Self::ConstKeyword => "ConstKeyword",
            Self::ContinueKeyword => "ContinueKeyword",
            Self::DebuggerKeyword => "DebuggerKeyword",
            Self::DefaultKeyword => "DefaultKeyword",
            Self::DeleteKeyword => "DeleteKeyword",
            Self::DoKeyword => "DoKeyword",
            Self::ElseKeyword => "ElseKeyword",
            Self::EnumKeyword => "EnumKeyword",
            Self::ExportKeyword => "ExportKeyword",
            Self::ExtendsKeyword => "ExtendsKeyword",
            Self::FalseKeyword => "FalseKeyword",
            Self::FinallyKeyword => "FinallyKeyword",
            Self::ForKeyword => "ForKeyword",
            Self::FunctionKeyword => "FunctionKeyword",
            Self::IfKeyword => "IfKeyword",
            Self::ImportKeyword => "ImportKeyword",
            Self::InKeyword => "InKeyword",
            Self::InstanceOfKeyword => "InstanceOfKeyword",
            Self::NewKeyword => "NewKeyword",
            Self::NullKeyword => "NullKeyword",
            Self::ReturnKeyword => "ReturnKeyword",
            Self::SuperKeyword => "SuperKeyword",
            Self::SwitchKeyword => "SwitchKeyword",
            Self::ThisKeyword => "ThisKeyword",
            Self::ThrowKeyword => "ThrowKeyword",
            Self::TrueKeyword => "TrueKeyword",
            Self::TryKeyword => "TryKeyword",
            Self::TypeOfKeyword => "TypeOfKeyword",
            Self::VarKeyword => "VarKeyword",
            Self::VoidKeyword => "VoidKeyword",
            Self::WhileKeyword => "WhileKeyword",
            Self::WithKeyword => "WithKeyword",
            Self::ImplementsKeyword => "ImplementsKeyword",
            Self::InterfaceKeyword => "InterfaceKeyword",
            Self::LetKeyword => "LetKeyword",
            Self::PackageKeyword => "PackageKeyword",
            Self::PrivateKeyword => "PrivateKeyword",
            Self::ProtectedKeyword => "ProtectedKeyword",
            Self::PublicKeyword => "PublicKeyword",
            Self::StaticKeyword => "StaticKeyword",
            Self::YieldKeyword => "YieldKeyword",
            Self::AbstractKeyword => "AbstractKeyword",
            Self::AccessorKeyword => "AccessorKeyword",
            Self::AsKeyword => "AsKeyword",
            Self::AssertsKeyword => "AssertsKeyword",
            Self::AssertKeyword => "AssertKeyword",
            Self::AnyKeyword => "AnyKeyword",
            Self::AsyncKeyword => "AsyncKeyword",
            Self::AwaitKeyword => "AwaitKeyword",
            Self::BooleanKeyword => "BooleanKeyword",
            Self::ConstructorKeyword => "ConstructorKeyword",
            Self::DeclareKeyword => "DeclareKeyword",
            Self::GetKeyword => "GetKeyword",
            Self::ImmediateKeyword => "ImmediateKeyword",
            Self::InferKeyword => "InferKeyword",
            Self::IntrinsicKeyword => "IntrinsicKeyword",
            Self::IsKeyword => "IsKeyword",
            Self::KeyOfKeyword => "KeyOfKeyword",
            Self::ModuleKeyword => "ModuleKeyword",
            Self::NamespaceKeyword => "NamespaceKeyword",
            Self::NeverKeyword => "NeverKeyword",
            Self::OutKeyword => "OutKeyword",
            Self::ReadonlyKeyword => "ReadonlyKeyword",
            Self::RequireKeyword => "RequireKeyword",
            Self::NumberKeyword => "NumberKeyword",
            Self::ObjectKeyword => "ObjectKeyword",
            Self::SatisfiesKeyword => "SatisfiesKeyword",
            Self::SetKeyword => "SetKeyword",
            Self::StringKeyword => "StringKeyword",
            Self::SymbolKeyword => "SymbolKeyword",
            Self::TypeKeyword => "TypeKeyword",
            Self::UndefinedKeyword => "UndefinedKeyword",
            Self::UniqueKeyword => "UniqueKeyword",
            Self::UnknownKeyword => "UnknownKeyword",
            Self::UsingKeyword => "UsingKeyword",
            Self::FromKeyword => "FromKeyword",
            Self::GlobalKeyword => "GlobalKeyword",
            Self::BigIntKeyword => "BigIntKeyword",
            Self::OverrideKeyword => "OverrideKeyword",
            Self::OfKeyword => "OfKeyword",
            Self::DeferKeyword => "DeferKeyword",
            Self::QualifiedName => "QualifiedName",
            Self::ComputedPropertyName => "ComputedPropertyName",
            Self::TypeParameter => "TypeParameter",
            Self::Parameter => "Parameter",
            Self::Decorator => "Decorator",
            Self::PropertySignature => "PropertySignature",
            Self::PropertyDeclaration => "PropertyDeclaration",
            Self::MethodSignature => "MethodSignature",
            Self::MethodDeclaration => "MethodDeclaration",
            Self::ClassStaticBlockDeclaration => "ClassStaticBlockDeclaration",
            Self::Constructor => "Constructor",
            Self::GetAccessor => "GetAccessor",
            Self::SetAccessor => "SetAccessor",
            Self::CallSignature => "CallSignature",
            Self::ConstructSignature => "ConstructSignature",
            Self::IndexSignature => "IndexSignature",
            Self::TypePredicate => "TypePredicate",
            Self::TypeReference => "TypeReference",
            Self::FunctionType => "FunctionType",
            Self::ConstructorType => "ConstructorType",
            Self::TypeQuery => "TypeQuery",
            Self::TypeLiteral => "TypeLiteral",
            Self::ArrayType => "ArrayType",
            Self::TupleType => "TupleType",
            Self::OptionalType => "OptionalType",
            Self::RestType => "RestType",
            Self::UnionType => "UnionType",
            Self::IntersectionType => "IntersectionType",
            Self::ConditionalType => "ConditionalType",
            Self::InferType => "InferType",
            Self::ParenthesizedType => "ParenthesizedType",
            Self::ThisType => "ThisType",
            Self::TypeOperator => "TypeOperator",
            Self::IndexedAccessType => "IndexedAccessType",
            Self::MappedType => "MappedType",
            Self::LiteralType => "LiteralType",
            Self::NamedTupleMember => "NamedTupleMember",
            Self::TemplateLiteralType => "TemplateLiteralType",
            Self::TemplateLiteralTypeSpan => "TemplateLiteralTypeSpan",
            Self::ImportType => "ImportType",
            Self::ObjectBindingPattern => "ObjectBindingPattern",
            Self::ArrayBindingPattern => "ArrayBindingPattern",
            Self::BindingElement => "BindingElement",
            Self::ArrayLiteralExpression => "ArrayLiteralExpression",
            Self::ObjectLiteralExpression => "ObjectLiteralExpression",
            Self::PropertyAccessExpression => "PropertyAccessExpression",
            Self::ElementAccessExpression => "ElementAccessExpression",
            Self::CallExpression => "CallExpression",
            Self::NewExpression => "NewExpression",
            Self::TaggedTemplateExpression => "TaggedTemplateExpression",
            Self::TypeAssertionExpression => "TypeAssertionExpression",
            Self::ParenthesizedExpression => "ParenthesizedExpression",
            Self::FunctionExpression => "FunctionExpression",
            Self::ArrowFunction => "ArrowFunction",
            Self::DeleteExpression => "DeleteExpression",
            Self::TypeOfExpression => "TypeOfExpression",
            Self::VoidExpression => "VoidExpression",
            Self::AwaitExpression => "AwaitExpression",
            Self::PrefixUnaryExpression => "PrefixUnaryExpression",
            Self::PostfixUnaryExpression => "PostfixUnaryExpression",
            Self::BinaryExpression => "BinaryExpression",
            Self::ConditionalExpression => "ConditionalExpression",
            Self::TemplateExpression => "TemplateExpression",
            Self::YieldExpression => "YieldExpression",
            Self::SpreadElement => "SpreadElement",
            Self::ClassExpression => "ClassExpression",
            Self::OmittedExpression => "OmittedExpression",
            Self::ExpressionWithTypeArguments => "ExpressionWithTypeArguments",
            Self::AsExpression => "AsExpression",
            Self::NonNullExpression => "NonNullExpression",
            Self::MetaProperty => "MetaProperty",
            Self::SyntheticExpression => "SyntheticExpression",
            Self::SatisfiesExpression => "SatisfiesExpression",
            Self::TemplateSpan => "TemplateSpan",
            Self::SemicolonClassElement => "SemicolonClassElement",
            Self::Block => "Block",
            Self::EmptyStatement => "EmptyStatement",
            Self::VariableStatement => "VariableStatement",
            Self::ExpressionStatement => "ExpressionStatement",
            Self::IfStatement => "IfStatement",
            Self::DoStatement => "DoStatement",
            Self::WhileStatement => "WhileStatement",
            Self::ForStatement => "ForStatement",
            Self::ForInStatement => "ForInStatement",
            Self::ForOfStatement => "ForOfStatement",
            Self::ContinueStatement => "ContinueStatement",
            Self::BreakStatement => "BreakStatement",
            Self::ReturnStatement => "ReturnStatement",
            Self::WithStatement => "WithStatement",
            Self::SwitchStatement => "SwitchStatement",
            Self::LabeledStatement => "LabeledStatement",
            Self::ThrowStatement => "ThrowStatement",
            Self::TryStatement => "TryStatement",
            Self::DebuggerStatement => "DebuggerStatement",
            Self::VariableDeclaration => "VariableDeclaration",
            Self::VariableDeclarationList => "VariableDeclarationList",
            Self::FunctionDeclaration => "FunctionDeclaration",
            Self::ClassDeclaration => "ClassDeclaration",
            Self::InterfaceDeclaration => "InterfaceDeclaration",
            Self::TypeAliasDeclaration => "TypeAliasDeclaration",
            Self::EnumDeclaration => "EnumDeclaration",
            Self::ModuleDeclaration => "ModuleDeclaration",
            Self::ModuleBlock => "ModuleBlock",
            Self::CaseBlock => "CaseBlock",
            Self::NamespaceExportDeclaration => "NamespaceExportDeclaration",
            Self::ImportEqualsDeclaration => "ImportEqualsDeclaration",
            Self::ImportDeclaration => "ImportDeclaration",
            Self::ImportClause => "ImportClause",
            Self::NamespaceImport => "NamespaceImport",
            Self::NamedImports => "NamedImports",
            Self::ImportSpecifier => "ImportSpecifier",
            Self::ExportAssignment => "ExportAssignment",
            Self::ExportDeclaration => "ExportDeclaration",
            Self::NamedExports => "NamedExports",
            Self::NamespaceExport => "NamespaceExport",
            Self::ExportSpecifier => "ExportSpecifier",
            Self::MissingDeclaration => "MissingDeclaration",
            Self::ExternalModuleReference => "ExternalModuleReference",
            Self::JsxElement => "JsxElement",
            Self::JsxSelfClosingElement => "JsxSelfClosingElement",
            Self::JsxOpeningElement => "JsxOpeningElement",
            Self::JsxClosingElement => "JsxClosingElement",
            Self::JsxFragment => "JsxFragment",
            Self::JsxOpeningFragment => "JsxOpeningFragment",
            Self::JsxClosingFragment => "JsxClosingFragment",
            Self::JsxAttribute => "JsxAttribute",
            Self::JsxAttributes => "JsxAttributes",
            Self::JsxSpreadAttribute => "JsxSpreadAttribute",
            Self::JsxExpression => "JsxExpression",
            Self::JsxNamespacedName => "JsxNamespacedName",
            Self::CaseClause => "CaseClause",
            Self::DefaultClause => "DefaultClause",
            Self::HeritageClause => "HeritageClause",
            Self::CatchClause => "CatchClause",
            Self::ImportAttributes => "ImportAttributes",
            Self::ImportAttribute => "ImportAttribute",
            Self::PropertyAssignment => "PropertyAssignment",
            Self::ShorthandPropertyAssignment => "ShorthandPropertyAssignment",
            Self::SpreadAssignment => "SpreadAssignment",
            Self::EnumMember => "EnumMember",
            Self::SourceFile => "SourceFile",
            Self::JsDocTypeExpression => "JSDocTypeExpression",
            Self::JsDocNameReference => "JSDocNameReference",
            Self::JsDocAllType => "JSDocAllType",
            Self::JsDocNullableType => "JSDocNullableType",
            Self::JsDocNonNullableType => "JSDocNonNullableType",
            Self::JsDocOptionalType => "JSDocOptionalType",
            Self::JsDocVariadicType => "JSDocVariadicType",
            Self::JsDoc => "JSDoc",
            Self::JsDocText => "JSDocText",
            Self::JsDocTypeLiteral => "JSDocTypeLiteral",
            Self::JsDocSignature => "JSDocSignature",
            Self::JsDocLink => "JSDocLink",
            Self::JsDocLinkCode => "JSDocLinkCode",
            Self::JsDocLinkPlain => "JSDocLinkPlain",
            Self::JsDocUnknownTag => "JSDocUnknownTag",
            Self::JsDocAugmentsTag => "JSDocAugmentsTag",
            Self::JsDocImplementsTag => "JSDocImplementsTag",
            Self::JsDocDeprecatedTag => "JSDocDeprecatedTag",
            Self::JsDocPublicTag => "JSDocPublicTag",
            Self::JsDocPrivateTag => "JSDocPrivateTag",
            Self::JsDocProtectedTag => "JSDocProtectedTag",
            Self::JsDocReadonlyTag => "JSDocReadonlyTag",
            Self::JsDocOverrideTag => "JSDocOverrideTag",
            Self::JsDocCallbackTag => "JSDocCallbackTag",
            Self::JsDocOverloadTag => "JSDocOverloadTag",
            Self::JsDocParameterTag => "JSDocParameterTag",
            Self::JsDocReturnTag => "JSDocReturnTag",
            Self::JsDocThisTag => "JSDocThisTag",
            Self::JsDocTypeTag => "JSDocTypeTag",
            Self::JsDocTemplateTag => "JSDocTemplateTag",
            Self::JsDocTypedefTag => "JSDocTypedefTag",
            Self::JsDocSeeTag => "JSDocSeeTag",
            Self::JsDocPropertyTag => "JSDocPropertyTag",
            Self::JsDocThrowsTag => "JSDocThrowsTag",
            Self::JsDocSatisfiesTag => "JSDocSatisfiesTag",
            Self::JsDocImportTag => "JSDocImportTag",
            Self::SyntaxList => "SyntaxList",
            Self::JsTypeAliasDeclaration => "JSTypeAliasDeclaration",
            Self::JsImportDeclaration => "JSImportDeclaration",
            Self::NotEmittedStatement => "NotEmittedStatement",
            Self::PartiallyEmittedExpression => "PartiallyEmittedExpression",
            Self::SyntheticReferenceExpression => "SyntheticReferenceExpression",
            Self::NotEmittedTypeElement => "NotEmittedTypeElement",
        }
    }

    #[must_use]
    pub const fn is_additive_operator(self) -> bool {
        matches!(self, Self::MinusToken | Self::PlusToken)
    }

    #[must_use]
    pub const fn is_additive_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::AmpersandEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::BarBarEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::EqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::MinusEqualsToken
                | Self::PercentEqualsToken
                | Self::PlusEqualsToken
                | Self::QuestionQuestionEqualsToken
                | Self::SlashEqualsToken
        )
    }

    #[must_use]
    pub const fn is_assignment_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::AmpersandAmpersandToken
                | Self::AmpersandEqualsToken
                | Self::AmpersandToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskEqualsToken
                | Self::AsteriskToken
                | Self::BarBarEqualsToken
                | Self::BarBarToken
                | Self::BarEqualsToken
                | Self::BarToken
                | Self::CaretEqualsToken
                | Self::CaretToken
                | Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::EqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusEqualsToken
                | Self::MinusToken
                | Self::PercentEqualsToken
                | Self::PercentToken
                | Self::PlusEqualsToken
                | Self::PlusToken
                | Self::QuestionQuestionEqualsToken
                | Self::QuestionQuestionToken
                | Self::SlashEqualsToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_binary_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::AmpersandAmpersandToken
                | Self::AmpersandEqualsToken
                | Self::AmpersandToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskEqualsToken
                | Self::AsteriskToken
                | Self::BarBarEqualsToken
                | Self::BarBarToken
                | Self::BarEqualsToken
                | Self::BarToken
                | Self::CaretEqualsToken
                | Self::CaretToken
                | Self::CommaToken
                | Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::EqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusEqualsToken
                | Self::MinusToken
                | Self::PercentEqualsToken
                | Self::PercentToken
                | Self::PlusEqualsToken
                | Self::PlusToken
                | Self::QuestionQuestionEqualsToken
                | Self::QuestionQuestionToken
                | Self::SlashEqualsToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_bitwise_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandToken | Self::BarToken | Self::CaretToken
        )
    }

    #[must_use]
    pub const fn is_bitwise_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AmpersandToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::BarToken
                | Self::CaretToken
                | Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_compound_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::AmpersandEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::BarBarEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::MinusEqualsToken
                | Self::PercentEqualsToken
                | Self::PlusEqualsToken
                | Self::QuestionQuestionEqualsToken
                | Self::SlashEqualsToken
        )
    }

    #[must_use]
    pub const fn is_equality_operator(self) -> bool {
        matches!(
            self,
            Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
        )
    }

    #[must_use]
    pub const fn is_equality_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_exponentiation_operator(self) -> bool {
        matches!(self, Self::AsteriskAsteriskToken)
    }

    #[must_use]
    pub const fn is_import_phase_modifier(self) -> bool {
        matches!(self, Self::DeferKeyword | Self::TypeKeyword)
    }

    #[must_use]
    pub const fn is_js_doc_node(self) -> bool {
        (self as u16) >= (Self::JsDocTypeExpression as u16)
            && (self as u16) <= (Self::JsDocImportTag as u16)
    }

    #[must_use]
    pub const fn is_jsx_token(self) -> bool {
        matches!(
            self,
            Self::ConflictMarkerTrivia
                | Self::EndOfFile
                | Self::JsxText
                | Self::JsxTextAllWhiteSpaces
                | Self::LessThanSlashToken
                | Self::LessThanToken
                | Self::OpenBraceToken
        )
    }

    #[must_use]
    pub const fn is_keyword_expression(self) -> bool {
        matches!(
            self,
            Self::FalseKeyword
                | Self::ImportKeyword
                | Self::NullKeyword
                | Self::SuperKeyword
                | Self::ThisKeyword
                | Self::TrueKeyword
        )
    }

    #[must_use]
    pub const fn is_keyword(self) -> bool {
        (self as u16) >= (Self::BreakKeyword as u16) && (self as u16) <= (Self::DeferKeyword as u16)
    }

    #[must_use]
    pub const fn is_keyword_type(self) -> bool {
        matches!(
            self,
            Self::AnyKeyword
                | Self::BigIntKeyword
                | Self::BooleanKeyword
                | Self::IntrinsicKeyword
                | Self::NeverKeyword
                | Self::NumberKeyword
                | Self::ObjectKeyword
                | Self::StringKeyword
                | Self::SymbolKeyword
                | Self::UndefinedKeyword
                | Self::UnknownKeyword
                | Self::VoidKeyword
        )
    }

    #[must_use]
    pub const fn is_literal(self) -> bool {
        (self as u16) >= (Self::NumericLiteral as u16)
            && (self as u16) <= (Self::NoSubstitutionTemplateLiteral as u16)
    }

    #[must_use]
    pub const fn is_logical_operator(self) -> bool {
        matches!(self, Self::AmpersandAmpersandToken | Self::BarBarToken)
    }

    #[must_use]
    pub const fn is_logical_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandToken
                | Self::AmpersandToken
                | Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::BarBarToken
                | Self::BarToken
                | Self::CaretToken
                | Self::EqualsEqualsEqualsToken
                | Self::EqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_logical_or_coalescing_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::BarBarEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }

    #[must_use]
    pub const fn is_modifier(self) -> bool {
        matches!(
            self,
            Self::AbstractKeyword
                | Self::AccessorKeyword
                | Self::AsyncKeyword
                | Self::ConstKeyword
                | Self::DeclareKeyword
                | Self::DefaultKeyword
                | Self::ExportKeyword
                | Self::InKeyword
                | Self::OutKeyword
                | Self::OverrideKeyword
                | Self::PrivateKeyword
                | Self::ProtectedKeyword
                | Self::PublicKeyword
                | Self::ReadonlyKeyword
                | Self::StaticKeyword
        )
    }

    #[must_use]
    pub const fn is_multiplicative_operator(self) -> bool {
        matches!(
            self,
            Self::AsteriskToken | Self::PercentToken | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_multiplicative_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::PercentToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_postfix_unary_operator(self) -> bool {
        matches!(self, Self::MinusMinusToken | Self::PlusPlusToken)
    }

    #[must_use]
    pub const fn is_prefix_unary_operator(self) -> bool {
        matches!(
            self,
            Self::ExclamationToken
                | Self::MinusMinusToken
                | Self::MinusToken
                | Self::PlusPlusToken
                | Self::PlusToken
                | Self::TildeToken
        )
    }

    #[must_use]
    pub const fn is_pseudo_literal(self) -> bool {
        matches!(
            self,
            Self::TemplateHead | Self::TemplateMiddle | Self::TemplateTail
        )
    }

    #[must_use]
    pub const fn is_punctuation(self) -> bool {
        (self as u16) >= (Self::OpenBraceToken as u16)
            && (self as u16) <= (Self::CaretEqualsToken as u16)
    }

    #[must_use]
    pub const fn is_relational_operator(self) -> bool {
        matches!(
            self,
            Self::GreaterThanEqualsToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanToken
        )
    }

    #[must_use]
    pub const fn is_relational_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::GreaterThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanToken
                | Self::InKeyword
                | Self::InstanceOfKeyword
                | Self::LessThanEqualsToken
                | Self::LessThanLessThanToken
                | Self::LessThanToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_shift_operator(self) -> bool {
        matches!(
            self,
            Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::LessThanLessThanToken
        )
    }

    #[must_use]
    pub const fn is_shift_operator_or_higher(self) -> bool {
        matches!(
            self,
            Self::AsteriskAsteriskToken
                | Self::AsteriskToken
                | Self::GreaterThanGreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::LessThanLessThanToken
                | Self::MinusToken
                | Self::PercentToken
                | Self::PlusToken
                | Self::SlashToken
        )
    }

    #[must_use]
    pub const fn is_token(self) -> bool {
        (self as u16) >= (Self::Unknown as u16) && (self as u16) <= (Self::DeferKeyword as u16)
    }

    #[must_use]
    pub const fn is_trivia(self) -> bool {
        matches!(
            self,
            Self::ConflictMarkerTrivia
                | Self::MultiLineCommentTrivia
                | Self::NewLineTrivia
                | Self::SingleLineCommentTrivia
                | Self::WhitespaceTrivia
        )
    }
}

impl TryFrom<u16> for SyntaxKind {
    type Error = ();

    #[allow(clippy::too_many_lines)]
    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::EndOfFile),
            2 => Ok(Self::SingleLineCommentTrivia),
            3 => Ok(Self::MultiLineCommentTrivia),
            4 => Ok(Self::NewLineTrivia),
            5 => Ok(Self::WhitespaceTrivia),
            6 => Ok(Self::ConflictMarkerTrivia),
            7 => Ok(Self::NonTextFileMarkerTrivia),
            8 => Ok(Self::NumericLiteral),
            9 => Ok(Self::BigIntLiteral),
            10 => Ok(Self::StringLiteral),
            11 => Ok(Self::JsxText),
            12 => Ok(Self::JsxTextAllWhiteSpaces),
            13 => Ok(Self::RegularExpressionLiteral),
            14 => Ok(Self::NoSubstitutionTemplateLiteral),
            15 => Ok(Self::TemplateHead),
            16 => Ok(Self::TemplateMiddle),
            17 => Ok(Self::TemplateTail),
            18 => Ok(Self::OpenBraceToken),
            19 => Ok(Self::CloseBraceToken),
            20 => Ok(Self::OpenParenToken),
            21 => Ok(Self::CloseParenToken),
            22 => Ok(Self::OpenBracketToken),
            23 => Ok(Self::CloseBracketToken),
            24 => Ok(Self::DotToken),
            25 => Ok(Self::DotDotDotToken),
            26 => Ok(Self::SemicolonToken),
            27 => Ok(Self::CommaToken),
            28 => Ok(Self::QuestionDotToken),
            29 => Ok(Self::LessThanToken),
            30 => Ok(Self::LessThanSlashToken),
            31 => Ok(Self::GreaterThanToken),
            32 => Ok(Self::LessThanEqualsToken),
            33 => Ok(Self::GreaterThanEqualsToken),
            34 => Ok(Self::EqualsEqualsToken),
            35 => Ok(Self::ExclamationEqualsToken),
            36 => Ok(Self::EqualsEqualsEqualsToken),
            37 => Ok(Self::ExclamationEqualsEqualsToken),
            38 => Ok(Self::EqualsGreaterThanToken),
            39 => Ok(Self::PlusToken),
            40 => Ok(Self::MinusToken),
            41 => Ok(Self::AsteriskToken),
            42 => Ok(Self::AsteriskAsteriskToken),
            43 => Ok(Self::SlashToken),
            44 => Ok(Self::PercentToken),
            45 => Ok(Self::PlusPlusToken),
            46 => Ok(Self::MinusMinusToken),
            47 => Ok(Self::LessThanLessThanToken),
            48 => Ok(Self::GreaterThanGreaterThanToken),
            49 => Ok(Self::GreaterThanGreaterThanGreaterThanToken),
            50 => Ok(Self::AmpersandToken),
            51 => Ok(Self::BarToken),
            52 => Ok(Self::CaretToken),
            53 => Ok(Self::ExclamationToken),
            54 => Ok(Self::TildeToken),
            55 => Ok(Self::AmpersandAmpersandToken),
            56 => Ok(Self::BarBarToken),
            57 => Ok(Self::QuestionToken),
            58 => Ok(Self::ColonToken),
            59 => Ok(Self::AtToken),
            60 => Ok(Self::QuestionQuestionToken),
            61 => Ok(Self::BacktickToken),
            62 => Ok(Self::HashToken),
            63 => Ok(Self::EqualsToken),
            64 => Ok(Self::PlusEqualsToken),
            65 => Ok(Self::MinusEqualsToken),
            66 => Ok(Self::AsteriskEqualsToken),
            67 => Ok(Self::AsteriskAsteriskEqualsToken),
            68 => Ok(Self::SlashEqualsToken),
            69 => Ok(Self::PercentEqualsToken),
            70 => Ok(Self::LessThanLessThanEqualsToken),
            71 => Ok(Self::GreaterThanGreaterThanEqualsToken),
            72 => Ok(Self::GreaterThanGreaterThanGreaterThanEqualsToken),
            73 => Ok(Self::AmpersandEqualsToken),
            74 => Ok(Self::BarEqualsToken),
            75 => Ok(Self::BarBarEqualsToken),
            76 => Ok(Self::AmpersandAmpersandEqualsToken),
            77 => Ok(Self::QuestionQuestionEqualsToken),
            78 => Ok(Self::CaretEqualsToken),
            79 => Ok(Self::Identifier),
            80 => Ok(Self::PrivateIdentifier),
            81 => Ok(Self::JsDocCommentTextToken),
            82 => Ok(Self::BreakKeyword),
            83 => Ok(Self::CaseKeyword),
            84 => Ok(Self::CatchKeyword),
            85 => Ok(Self::ClassKeyword),
            86 => Ok(Self::ConstKeyword),
            87 => Ok(Self::ContinueKeyword),
            88 => Ok(Self::DebuggerKeyword),
            89 => Ok(Self::DefaultKeyword),
            90 => Ok(Self::DeleteKeyword),
            91 => Ok(Self::DoKeyword),
            92 => Ok(Self::ElseKeyword),
            93 => Ok(Self::EnumKeyword),
            94 => Ok(Self::ExportKeyword),
            95 => Ok(Self::ExtendsKeyword),
            96 => Ok(Self::FalseKeyword),
            97 => Ok(Self::FinallyKeyword),
            98 => Ok(Self::ForKeyword),
            99 => Ok(Self::FunctionKeyword),
            100 => Ok(Self::IfKeyword),
            101 => Ok(Self::ImportKeyword),
            102 => Ok(Self::InKeyword),
            103 => Ok(Self::InstanceOfKeyword),
            104 => Ok(Self::NewKeyword),
            105 => Ok(Self::NullKeyword),
            106 => Ok(Self::ReturnKeyword),
            107 => Ok(Self::SuperKeyword),
            108 => Ok(Self::SwitchKeyword),
            109 => Ok(Self::ThisKeyword),
            110 => Ok(Self::ThrowKeyword),
            111 => Ok(Self::TrueKeyword),
            112 => Ok(Self::TryKeyword),
            113 => Ok(Self::TypeOfKeyword),
            114 => Ok(Self::VarKeyword),
            115 => Ok(Self::VoidKeyword),
            116 => Ok(Self::WhileKeyword),
            117 => Ok(Self::WithKeyword),
            118 => Ok(Self::ImplementsKeyword),
            119 => Ok(Self::InterfaceKeyword),
            120 => Ok(Self::LetKeyword),
            121 => Ok(Self::PackageKeyword),
            122 => Ok(Self::PrivateKeyword),
            123 => Ok(Self::ProtectedKeyword),
            124 => Ok(Self::PublicKeyword),
            125 => Ok(Self::StaticKeyword),
            126 => Ok(Self::YieldKeyword),
            127 => Ok(Self::AbstractKeyword),
            128 => Ok(Self::AccessorKeyword),
            129 => Ok(Self::AsKeyword),
            130 => Ok(Self::AssertsKeyword),
            131 => Ok(Self::AssertKeyword),
            132 => Ok(Self::AnyKeyword),
            133 => Ok(Self::AsyncKeyword),
            134 => Ok(Self::AwaitKeyword),
            135 => Ok(Self::BooleanKeyword),
            136 => Ok(Self::ConstructorKeyword),
            137 => Ok(Self::DeclareKeyword),
            138 => Ok(Self::GetKeyword),
            139 => Ok(Self::ImmediateKeyword),
            140 => Ok(Self::InferKeyword),
            141 => Ok(Self::IntrinsicKeyword),
            142 => Ok(Self::IsKeyword),
            143 => Ok(Self::KeyOfKeyword),
            144 => Ok(Self::ModuleKeyword),
            145 => Ok(Self::NamespaceKeyword),
            146 => Ok(Self::NeverKeyword),
            147 => Ok(Self::OutKeyword),
            148 => Ok(Self::ReadonlyKeyword),
            149 => Ok(Self::RequireKeyword),
            150 => Ok(Self::NumberKeyword),
            151 => Ok(Self::ObjectKeyword),
            152 => Ok(Self::SatisfiesKeyword),
            153 => Ok(Self::SetKeyword),
            154 => Ok(Self::StringKeyword),
            155 => Ok(Self::SymbolKeyword),
            156 => Ok(Self::TypeKeyword),
            157 => Ok(Self::UndefinedKeyword),
            158 => Ok(Self::UniqueKeyword),
            159 => Ok(Self::UnknownKeyword),
            160 => Ok(Self::UsingKeyword),
            161 => Ok(Self::FromKeyword),
            162 => Ok(Self::GlobalKeyword),
            163 => Ok(Self::BigIntKeyword),
            164 => Ok(Self::OverrideKeyword),
            165 => Ok(Self::OfKeyword),
            166 => Ok(Self::DeferKeyword),
            167 => Ok(Self::QualifiedName),
            168 => Ok(Self::ComputedPropertyName),
            169 => Ok(Self::TypeParameter),
            170 => Ok(Self::Parameter),
            171 => Ok(Self::Decorator),
            172 => Ok(Self::PropertySignature),
            173 => Ok(Self::PropertyDeclaration),
            174 => Ok(Self::MethodSignature),
            175 => Ok(Self::MethodDeclaration),
            176 => Ok(Self::ClassStaticBlockDeclaration),
            177 => Ok(Self::Constructor),
            178 => Ok(Self::GetAccessor),
            179 => Ok(Self::SetAccessor),
            180 => Ok(Self::CallSignature),
            181 => Ok(Self::ConstructSignature),
            182 => Ok(Self::IndexSignature),
            183 => Ok(Self::TypePredicate),
            184 => Ok(Self::TypeReference),
            185 => Ok(Self::FunctionType),
            186 => Ok(Self::ConstructorType),
            187 => Ok(Self::TypeQuery),
            188 => Ok(Self::TypeLiteral),
            189 => Ok(Self::ArrayType),
            190 => Ok(Self::TupleType),
            191 => Ok(Self::OptionalType),
            192 => Ok(Self::RestType),
            193 => Ok(Self::UnionType),
            194 => Ok(Self::IntersectionType),
            195 => Ok(Self::ConditionalType),
            196 => Ok(Self::InferType),
            197 => Ok(Self::ParenthesizedType),
            198 => Ok(Self::ThisType),
            199 => Ok(Self::TypeOperator),
            200 => Ok(Self::IndexedAccessType),
            201 => Ok(Self::MappedType),
            202 => Ok(Self::LiteralType),
            203 => Ok(Self::NamedTupleMember),
            204 => Ok(Self::TemplateLiteralType),
            205 => Ok(Self::TemplateLiteralTypeSpan),
            206 => Ok(Self::ImportType),
            207 => Ok(Self::ObjectBindingPattern),
            208 => Ok(Self::ArrayBindingPattern),
            209 => Ok(Self::BindingElement),
            210 => Ok(Self::ArrayLiteralExpression),
            211 => Ok(Self::ObjectLiteralExpression),
            212 => Ok(Self::PropertyAccessExpression),
            213 => Ok(Self::ElementAccessExpression),
            214 => Ok(Self::CallExpression),
            215 => Ok(Self::NewExpression),
            216 => Ok(Self::TaggedTemplateExpression),
            217 => Ok(Self::TypeAssertionExpression),
            218 => Ok(Self::ParenthesizedExpression),
            219 => Ok(Self::FunctionExpression),
            220 => Ok(Self::ArrowFunction),
            221 => Ok(Self::DeleteExpression),
            222 => Ok(Self::TypeOfExpression),
            223 => Ok(Self::VoidExpression),
            224 => Ok(Self::AwaitExpression),
            225 => Ok(Self::PrefixUnaryExpression),
            226 => Ok(Self::PostfixUnaryExpression),
            227 => Ok(Self::BinaryExpression),
            228 => Ok(Self::ConditionalExpression),
            229 => Ok(Self::TemplateExpression),
            230 => Ok(Self::YieldExpression),
            231 => Ok(Self::SpreadElement),
            232 => Ok(Self::ClassExpression),
            233 => Ok(Self::OmittedExpression),
            234 => Ok(Self::ExpressionWithTypeArguments),
            235 => Ok(Self::AsExpression),
            236 => Ok(Self::NonNullExpression),
            237 => Ok(Self::MetaProperty),
            238 => Ok(Self::SyntheticExpression),
            239 => Ok(Self::SatisfiesExpression),
            240 => Ok(Self::TemplateSpan),
            241 => Ok(Self::SemicolonClassElement),
            242 => Ok(Self::Block),
            243 => Ok(Self::EmptyStatement),
            244 => Ok(Self::VariableStatement),
            245 => Ok(Self::ExpressionStatement),
            246 => Ok(Self::IfStatement),
            247 => Ok(Self::DoStatement),
            248 => Ok(Self::WhileStatement),
            249 => Ok(Self::ForStatement),
            250 => Ok(Self::ForInStatement),
            251 => Ok(Self::ForOfStatement),
            252 => Ok(Self::ContinueStatement),
            253 => Ok(Self::BreakStatement),
            254 => Ok(Self::ReturnStatement),
            255 => Ok(Self::WithStatement),
            256 => Ok(Self::SwitchStatement),
            257 => Ok(Self::LabeledStatement),
            258 => Ok(Self::ThrowStatement),
            259 => Ok(Self::TryStatement),
            260 => Ok(Self::DebuggerStatement),
            261 => Ok(Self::VariableDeclaration),
            262 => Ok(Self::VariableDeclarationList),
            263 => Ok(Self::FunctionDeclaration),
            264 => Ok(Self::ClassDeclaration),
            265 => Ok(Self::InterfaceDeclaration),
            266 => Ok(Self::TypeAliasDeclaration),
            267 => Ok(Self::EnumDeclaration),
            268 => Ok(Self::ModuleDeclaration),
            269 => Ok(Self::ModuleBlock),
            270 => Ok(Self::CaseBlock),
            271 => Ok(Self::NamespaceExportDeclaration),
            272 => Ok(Self::ImportEqualsDeclaration),
            273 => Ok(Self::ImportDeclaration),
            274 => Ok(Self::ImportClause),
            275 => Ok(Self::NamespaceImport),
            276 => Ok(Self::NamedImports),
            277 => Ok(Self::ImportSpecifier),
            278 => Ok(Self::ExportAssignment),
            279 => Ok(Self::ExportDeclaration),
            280 => Ok(Self::NamedExports),
            281 => Ok(Self::NamespaceExport),
            282 => Ok(Self::ExportSpecifier),
            283 => Ok(Self::MissingDeclaration),
            284 => Ok(Self::ExternalModuleReference),
            285 => Ok(Self::JsxElement),
            286 => Ok(Self::JsxSelfClosingElement),
            287 => Ok(Self::JsxOpeningElement),
            288 => Ok(Self::JsxClosingElement),
            289 => Ok(Self::JsxFragment),
            290 => Ok(Self::JsxOpeningFragment),
            291 => Ok(Self::JsxClosingFragment),
            292 => Ok(Self::JsxAttribute),
            293 => Ok(Self::JsxAttributes),
            294 => Ok(Self::JsxSpreadAttribute),
            295 => Ok(Self::JsxExpression),
            296 => Ok(Self::JsxNamespacedName),
            297 => Ok(Self::CaseClause),
            298 => Ok(Self::DefaultClause),
            299 => Ok(Self::HeritageClause),
            300 => Ok(Self::CatchClause),
            301 => Ok(Self::ImportAttributes),
            302 => Ok(Self::ImportAttribute),
            303 => Ok(Self::PropertyAssignment),
            304 => Ok(Self::ShorthandPropertyAssignment),
            305 => Ok(Self::SpreadAssignment),
            306 => Ok(Self::EnumMember),
            307 => Ok(Self::SourceFile),
            308 => Ok(Self::JsDocTypeExpression),
            309 => Ok(Self::JsDocNameReference),
            310 => Ok(Self::JsDocAllType),
            311 => Ok(Self::JsDocNullableType),
            312 => Ok(Self::JsDocNonNullableType),
            313 => Ok(Self::JsDocOptionalType),
            314 => Ok(Self::JsDocVariadicType),
            315 => Ok(Self::JsDoc),
            316 => Ok(Self::JsDocText),
            317 => Ok(Self::JsDocTypeLiteral),
            318 => Ok(Self::JsDocSignature),
            319 => Ok(Self::JsDocLink),
            320 => Ok(Self::JsDocLinkCode),
            321 => Ok(Self::JsDocLinkPlain),
            322 => Ok(Self::JsDocUnknownTag),
            323 => Ok(Self::JsDocAugmentsTag),
            324 => Ok(Self::JsDocImplementsTag),
            325 => Ok(Self::JsDocDeprecatedTag),
            326 => Ok(Self::JsDocPublicTag),
            327 => Ok(Self::JsDocPrivateTag),
            328 => Ok(Self::JsDocProtectedTag),
            329 => Ok(Self::JsDocReadonlyTag),
            330 => Ok(Self::JsDocOverrideTag),
            331 => Ok(Self::JsDocCallbackTag),
            332 => Ok(Self::JsDocOverloadTag),
            333 => Ok(Self::JsDocParameterTag),
            334 => Ok(Self::JsDocReturnTag),
            335 => Ok(Self::JsDocThisTag),
            336 => Ok(Self::JsDocTypeTag),
            337 => Ok(Self::JsDocTemplateTag),
            338 => Ok(Self::JsDocTypedefTag),
            339 => Ok(Self::JsDocSeeTag),
            340 => Ok(Self::JsDocPropertyTag),
            341 => Ok(Self::JsDocThrowsTag),
            342 => Ok(Self::JsDocSatisfiesTag),
            343 => Ok(Self::JsDocImportTag),
            344 => Ok(Self::SyntaxList),
            345 => Ok(Self::JsTypeAliasDeclaration),
            346 => Ok(Self::JsImportDeclaration),
            347 => Ok(Self::NotEmittedStatement),
            348 => Ok(Self::PartiallyEmittedExpression),
            349 => Ok(Self::SyntheticReferenceExpression),
            350 => Ok(Self::NotEmittedTypeElement),
            _ => Err(()),
        }
    }
}
